# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Bluekola' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for Bluekola
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'RCTImage' # <- Add this line
  ]
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec', :modular_headers => false
  pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'
  


  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == "React"
        target.remove_from_project
      end
    end
  end

  target 'BluekolaTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

